To Do React tutorial PR #1
codehass/todo-react pull request #2
Opened 2023-01-17 14:04 UTC by codehass

### In this pull request : 
- Set up Gitflow
- Create React app
- Add linters

2023-01-17 15:38 UTC, Wahaj-Ali commented on README.md
> +- [Live Demo Link](https://yourdeployedapplicationlink.com)
Kindly add the link to the live demo, if not available then you can remove this section from your Readme file to make it look impressive.

2023-01-17 15:38 UTC, Wahaj-Ali commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Please make sure to add License here.

2023-01-17 15:48 UTC, Wahaj-Ali requested changes
Dear @codehass Your project is not working. It is giving the following errors:
![Screenshot 2023-01-17 202840](https://user-images.githubusercontent.com/111431787/212940946-24563397-f759-4405-91c8-445b49199d77.png)

**Please make sure to eliminate these errors and request for a re-review.**

- Linter errors fixed ❌ 
- Correct GitFlow followed ✅ 
- Best practices used  for HTML, CSS, JavaScript ✅
-  Descriptive commit history ❌ 

**You can also look for the in-line comments below to make further changes.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on Slack

2023-01-17 16:32 UTC, codehass commented
Thank you @Wahaj-Ali for all your feedback 😁 I will add all the changes. 👌

2023-01-18 10:05 UTC, Wahaj-Ali approved these changes
Hi @codehass 
### **Status: Approved**
Your project is complete and working fine 💯 
It's time to merge 🎉

![well-done](https://user-images.githubusercontent.com/111431787/213140677-e3feb8b3-2546-467c-accb-11b99a0f185b.gif)

### Highlights

- No linter errors ✅ 
- Correct GitFlow followed ✅ 
- Used (JavaScript, HTML, CSS) best practices ✅ 
- Good descriptive PR✅ 
- Commits are meaningful ✅ 
- Working App ✅ 
- Correct .gitignore file ✅ 
- Correct implementation of "Components, Lifting state up, Hooks" ✅ 

### **Optional Suggestions**
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

2023-01-18 10:06 UTC, merged